AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  TransformData:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: src/
      FunctionName: SW-lambda-TransformData
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::12345678:role/sw-lambda-role'
      Events:
        Stream:
          Type: Kinesis
          Properties:
            Stream: arn:aws:kinesis:us-east-1:12345678:stream/sw-TransformData
            StartingPosition: TRIM_HORIZON
            BatchSize: 100
      VpcConfig:
        SecurityGroupIds:
          - sg-123456789
        SubnetIds:
          - subnet-1234
          - subnet-5678
      Environment:
        Variables:
          BUCKET_NAME: sw-s3-bucket
          COLLECTION_NAME: sw_data
          DATABASE_NAME: SW_RAW
          PEM_FILE_LOC_PREFIX: //tmp//
          PEM_FILE_NAME: rds-combined-ca-bundle.pem
      Layers:
        - 'arn:aws:lambda:us-east-1:12345678:layer:pymongo38:1'

